# Generated by Django 4.2.1 on 2023-07-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_course_is_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourse',
            name='courseprogress',
            field=models.FloatField(max_length=100),
        ),
    ]
